// @generated by scripts/generate_native_flags.py; do not edit.
pub const ENGINE_ALIASES: &[&str] = &["pdflatex", "latex", "xelatex", "lualatex", "platex", "uplatex", "pdftex", "tex", "etex", "luatex", "luahbtex", "dvilualatex", "dviluatex", "xetex", "pdfetex"];
pub const STUB_BIB: &[&str] = &["bibtex", "bibtex8", "bibtexu"];
pub const PROXY_OR_STUB: &[&str] = &["biber", "makeindex", "xindy", "upmendex"];
pub const STUB_DVI: &[&str] = &["dvips", "dvipdfm", "dvipdfmx", "dvipdf", "xdvipdfmx", "dvitype", "dvicopy", "dvipos", "dvidvi"];
pub const SILENT_STUBS: &[&str] = &["mktexlsr", "texhash"];
pub const INFORMATIVE_MAINTENANCE: &[&str] = &["mktexfmt", "mktexpk", "mktextfm", "fmtutil", "fmtutil-sys", "updmap", "updmap-sys", "texconfig"];
pub const FONT_STUBS: &[&str] = &["tftopl", "pltotf", "vftovp", "vptovf", "gftopk", "gftype", "afm2tfm", "otftotfm"];
pub const METAFONT_STUBS: &[&str] = &["mf", "mpost", "mft", "tangle", "weave"];
pub const CONTEXT_STUBS: &[&str] = &["context", "texexec"];
pub const SPECIAL_STUBS: &[&str] = &["tlmgr", "texdoc"];
pub const PROXIES: &[&str] = &["pdftotext", "pdfinfo", "pdfimages", "pdftoppm", "pdftocairo", "pdfunite", "pdfseparate", "pdftops", "qpdf"];
pub const GS_TOOLS: &[&str] = &["epstopdf", "eps2eps", "ps2pdf", "pdfcrop"];
pub const IGNORED_FLAGS: &[&str] = &["8bit", "allow-orphan-aux", "babel", "c-style-errors", "cnf-line", "disable-enctex", "disable-installer", "disable-shell-escape", "disable-write18", "draft", "draftmode", "dvi", "enable-8bit-chars", "enable-enctex", "enable-installer", "enc", "etex", "file-line-error", "file-line-error-style", "fmt", "halt-on-error", "ini", "initialize", "ipc", "ipc-start", "latex", "luajittex", "luatex", "luatex0", "maketex", "max-fonts", "max-pages", "max-strings", "no-allow-orphan-aux", "no-dvi", "no-enable-8bit-chars", "no-file-line-error", "no-maketex", "no-mktexfmt", "no-mktexpk", "no-parse-first-line", "no-pdf", "no-pdf-output", "no-shell-escape", "output-comment", "pagectr", "pagetranslate", "parse-first-line", "pdf", "pdftex", "preload", "progname", "recorder", "shell-restricted", "src-specials", "tcx", "translate-file", "undump", "utf8", "xetex"];
pub const MEMORY_KNOBS: &[&str] = &["buf-size", "error-line", "extra-mem-bot", "extra-mem-top", "font-max", "font-mem-size", "half-error-line", "hash-size", "main-memory", "max-in-open", "max-print-line", "nest-size", "param-size", "pkin", "pool-size", "save-size", "stack-size", "strings", "tfm"];
pub const ENGINE_PATH_VARS: &[&str] = &["TEXINPUTS", "BIBINPUTS", "BSTINPUTS", "INDEXSTYLE"];
