#!/usr/bin/env python3
"""Generate Rust command-farm tables from the Python reference tables."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
from tectdist import flags  # noqa: E402

OUT = os.path.join(ROOT, "crates", "tectdist-tools", "src", "generated_flags.rs")


def array(name, values):
    return "pub const %s: &[&str] = &[%s];\n" % (
        name, ", ".join('"%s"' % value for value in values))


def render():
    sets = (("ENGINE_ALIASES", flags.ENGINES), ("STUB_BIB", flags.STUB_BIB),
            ("PROXY_OR_STUB", flags.PROXY_OR_STUB), ("STUB_DVI", flags.STUB_DVI),
            ("SILENT_STUBS", flags.STUB_MNT_SILENT),
            ("INFORMATIVE_MAINTENANCE", flags.STUB_MNT_VERBOSE),
            ("FONT_STUBS", flags.STUB_FNT), ("METAFONT_STUBS", flags.STUB_MF),
            ("CONTEXT_STUBS", flags.STUB_CONTEXT), ("SPECIAL_STUBS", flags.STUB_SPECIAL),
            ("PROXIES", flags.PROXIES), ("GS_TOOLS", flags.GS_TOOLS),
            ("IGNORED_FLAGS", sorted(flags.IGNORED_FLAGS)),
            ("MEMORY_KNOBS", sorted(flags.MEMORY_KNOBS)),
            ("ENGINE_PATH_VARS", flags.ENGINE_PATH_VARS))
    return "// @generated by scripts/generate_native_flags.py; do not edit.\n" + "".join(array(*item) for item in sets)


def main():
    content = render()
    existing = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if "--check" in sys.argv:
        if existing != content:
            print("native flag tables are stale; run scripts/generate_native_flags.py")
            return 1
        print("native flag tables: OK")
        return 0
    with open(OUT, "w", encoding="utf-8") as stream:
        stream.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
